### ISSUE TITLE
Warezcdn kodi

### ISSUE THREAD

**Issue by icarok99** [Huuuuuugo/warezcdn.py#1]
Can you help with an addon for kodi that uses warezcdn?

**Comment by icarok99** [comment]
https://www.mediafire.com/file/ypewh2ufgqayd6n/plugin.video.thethunder-1.1.5.zip/file

**Comment by Huuuuuugo** [comment]
I've never used kodi, but maybe I can help, what do you need?

**Comment by icarok99** [comment]
> I've never used kodi, but maybe I can help, what do you need?

Addon repository https://oneplayhd.com/oneplay/One.repo-1.11.zip

warez.py file if you don't want to install kodi

https://www.mediafire.com/file/kbw4dpqxzpcl2vq/warez.py/file

**Comment by icarok99** [comment]
This is the addon that uses warezcdn 

![Screenshot_2024-12-08-08-30-59-736_org xbmc kodi](https://github.com/user-attachments/assets/85ee6e4f-0cbc-4bf4-b11b-c78271fca7ba)

**Comment by Huuuuuugo** [comment]
vou dar uma olhada nisso quando tiver um tempo livre

**Comment by Huuuuuugo** [comment]
esse repósitório não existe no github? tu consegue enviar algum arquivo de teste pra esse script `warez.py`?

**Comment by icarok99** [comment]
https://github.com/zoreu/OneRepo

**Comment by icarok99** [comment]
Esse addon só dar para instalar pelo repositório por causa das dependências.

**Comment by icarok99** [comment]
É o addon thunder que utiliza o script warez.py

**Comment by icarok99** [comment]
Aqui o tutorial de como instalar o repositório e o addon 

https://www.wirelesshack.org/how-to-install-thunder-kodi-add-on.html

**Comment by icarok99** [comment]
> esse repósitório não existe no github? tu consegue enviar algum arquivo de teste pra esse script `warez.py`?

É o addon thunder que utiliza o script warez.py

**Comment by Huuuuuugo** [comment]
Eu acabei de mandar as alterações que fiz no arquivo `warez.py` pra [esse repositório](https://github.com/Huuuuuugo/warez-kodi-fix). Por enquanto eu só alterei o método que coleta os links dos arquivos de vídeo de filmes e episódios de séries, ainda faltam alguns outros métodos que ainda não vi exatamente o que fazem. 
Eu não instalei o kodi pra testar, mas acho que ainda não deve estar funcionando. Amanhã eu vejo se consigo consertar o resto.

**Comment by icarok99** [comment]
> Eu acabei de mandar as alterações que fiz no arquivo `warez.py` pra [esse repositório](https://github.com/Huuuuuugo/warez-kodi-fix). Por enquanto eu só alterei o método que coleta os links dos arquivos de vídeo de filmes e episódios de séries, ainda faltam alguns outros métodos que ainda não vi exatamente o que fazem. Eu não instalei o kodi pra testar, mas acho que ainda não deve estar funcionando. Amanhã eu vejo se consigo consertar o resto.

Ok e muito obrigado pela ajuda.

**Comment by Huuuuuugo** [comment]
Acabei de mandar as últimas alterações pra aquele mesmo repositório. Aparentemente os métodos que faltavam serviam apenas pra separar os links do vídeo e de legenda da url retornada naquele primeiro método que corrigi, então foi bem tranquilo de arrumar.
Porém, como eu não testei no kodi, não sei dizer se vai funcionar corretamente, o que sei é que todos os métodos desse arquivo `warez.py` foram corrigidos pra fazer o que eu acredito que eles foram programados pra fazer.
Espero ter ajudado👍

**Comment by icarok99** [comment]
> Acabei de mandar as últimas alterações pra aquele mesmo repositório. Aparentemente os métodos que faltavam serviam apenas pra separar os links do vídeo e de legenda da url retornada naquele primeiro método que corrigi, então foi bem tranquilo de arrumar. Porém, como eu não testei no kodi, não sei dizer se vai funcionar corretamente, o que sei é que todos os métodos desse arquivo `warez.py` foram corrigidos pra fazer o que eu acredito que eles foram programados pra fazer. Espero ter ajudado👍

Servidor warezcdn está obtendo esse link https://basseqwevewcewcewecwcw.xyz/video/d403e04fd46fd004b31833bd0747c4ba 

invés do https://basseqwevewcewcewecwcw.xyz/player/index.php?data=d403e04fd46fd004b31833bd0747c4ba&do=getVideo

**Comment by Huuuuuugo** [comment]
Abrindo no navegador os dois links parecem funcionar da mesma forma. O vídeo precisa seguir esse formato pra funcionar no kodi? Se sim, acho que posso modificar rapidinho a url retornada pra seguir esse formato.

**Comment by icarok99** [comment]
Essa é a mensagem de log quando tenta reproduzir 

Open - error probing input format, https://basseqwevewcewcewecwcw.xyz/video/d403e04fd46fd004b31833bd0747c4ba

**Comment by icarok99** [comment]
Com mixdrop também 

Open - error probing input format, https://mixdrop.ps/e/mkve04w3fg4901

**Comment by Huuuuuugo** [comment]
Mandei as alteração dos links warezcdn lá pro repositório.

**Comment by Huuuuuugo** [comment]
> Com mixdrop também
> 
> Open - error probing input format, https://mixdrop.ps/e/mkve04w3fg4901

Qual é o formato que o kodi espera pros links do mixdrop?

**Comment by icarok99** [comment]
> > Com mixdrop também
> > Open - error probing input format, https://mixdrop.ps/e/mkve04w3fg4901
> 
> Qual é o formato que o kodi espera pros links do mixdrop?

Mp4

**Comment by icarok99** [comment]
Exemplo do link retornado do resolverurl

https://s-delivery31.mxdcontent.net/v/fd8b67921c8a8e83a42c60d5510302de.mp4?s=hao6PXlrBljOizvyJ66lKw&e=1618978536&_t=1618957850

**Comment by Huuuuuugo** [comment]
Ah sim, acho que entendi. Ele quer o link direto do vídeo, não do player, certo? Isso complica um pouco mais as coisas nos links do mixdrop, mas acho que ainda dá pra resolver. Vou dar uma olhada nisso amanhã.

**Comment by Huuuuuugo** [comment]
Mas e o link do warezcdn? funcionou formatando a url daquele jeito?

**Comment by icarok99** [comment]
> Mas e o link do warezcdn? funcionou formatando a url daquele jeito?

![Screenshot_2024-12-11-17-00-23-642_org xbmc kodi](https://github.com/user-attachments/assets/3c1ed80a-6fb4-4b40-baef-225263b45bd3)
Não

**Comment by Huuuuuugo** [comment]
Talvez eu consiga consertar rapidinho esse do warezcdn agora que entendi o problema. Vou ver aqui.

**Comment by icarok99** [comment]
> Talvez eu consiga consertar rapidinho esse do warezcdn agora que entendi o problema. Vou ver aqui.

Como você não tá com kodi instalado eu coloquei no github os arquivos do addon https://github.com/icarok99/warez-kodi-fix

**Comment by Huuuuuugo** [comment]
Acabei de mandar as alterações pro repositório. Agora os métodos resolvers retornam o link direto do arquivo m3u8 do vídeo, que é o que contém o vídeo em si. Isso deve ser o suficiente pros links do warezcdn funcionarem.
Testa aí e me diz se deu certo.

**Comment by Huuuuuugo** [comment]
> > Talvez eu consiga consertar rapidinho esse do warezcdn agora que entendi o problema. Vou ver aqui.
> 
> Como você não tá com kodi instalado eu coloquei no github os arquivos do addon https://github.com/icarok99/warez-kodi-fix

Ok, depois vou ver se acho uma biblioteca pra deobfuscar javascript nesse repositório, porque isso é a única coisa que falta pra pegar os arquivos mp4 do mixdrop.

**Comment by icarok99** [comment]
VideoPlayer::OpenFile: https://basseqwevewcewcewecwcw.xyz/video/450fc92852e1ca2963c0ee18e586c9c5
2024-12-11 17:32:07.181 T:12645    info <general>: Creating InputStream
2024-12-11 17:32:08.119 T:12645    info <general>: Creating Demuxer
2024-12-11 17:32:08.392 T:12645   error <general>: Open - error probing input format, https://basseqwevewcewcewecwcw.xyz/video/450fc92852e1ca2963c0ee18e586c9c5
2024-12-11 17:32:08.392 T:12645   error <general>: OpenDemuxStream - Error creating demuxer
2024-12-11 17:32:08.392 T:12645    info <general>: CVideoPlayer::OnExit()

**Comment by Huuuuuugo** [comment]
Tem certeza que tá usando a versão mais recente do `warez.py`? O link retornado deveria ser algo tipo isso: https://basseqwevewcewcewecwcw.xyz/m3/QlNKRXBMcWgwVU84QnBQakZyRzgrS0ZjbU5zRExXSWZla3Q3WWphaDNqV2xRa1NTV2lXblZBRnlEVEtNTkpGeFVIS042SFlJdnNxWHU0akp1cGFhSkVkbWk5OU9zODNMbmlPMjl0ckVDQW4wZ1MvUDNhSnlsVjNrK0NWOUFGM3NLcmxpS29CaXh6aDhPTldSK2Q5TjRRWlNrdUFoRlNsTUpYalBHS0Q2U1RFa2tLOUo1dzhZR0NINDdoUHpzM0kvSVBTcnJKVnE0N2IrM3M0SFlWcFMvTmZaemVXdURzdVd4bGdsM2Q1TnR5RE1MVllqazJjMFM0VjY1N1J6UzkwakorMWY3QTdBNHdwVUE3cWNaZXRxTlZMRUkweGw2QTdxS3g5S0VhRzI5Rmc9

**Comment by icarok99** [comment]
> > > Talvez eu consiga consertar rapidinho esse do warezcdn agora que entendi o problema. Vou ver aqui.
> > 
> > 
> > Como você não tá com kodi instalado eu coloquei no github os arquivos do addon https://github.com/icarok99/warez-kodi-fix
> 
> Ok, depois vou ver se acho uma biblioteca pra deobfuscar javascript nesse repositório, porque isso é a única coisa que falta pra pegar os arquivos mp4 do mixdrop.

Com resolvers.py é possível obter o link do mixdrop

**Comment by icarok99** [comment]
> Tem certeza que tá usando a versão mais recente do `warez.py`? O link retornado deveria ser algo tipo isso: https://basseqwevewcewcewecwcw.xyz/m3/QlNKRXBMcWgwVU84QnBQakZyRzgrS0ZjbU5zRExXSWZla3Q3WWphaDNqV2xRa1NTV2lXblZBRnlEVEtNTkpGeFVIS042SFlJdnNxWHU0akp1cGFhSkVkbWk5OU9zODNMbmlPMjl0ckVDQW4wZ1MvUDNhSnlsVjNrK0NWOUFGM3NLcmxpS29CaXh6aDhPTldSK2Q5TjRRWlNrdUFoRlNsTUpYalBHS0Q2U1RFa2tLOUo1dzhZR0NINDdoUHpzM0kvSVBTcnJKVnE0N2IrM3M0SFlWcFMvTmZaemVXdURzdVd4bGdsM2Q1TnR5RE1MVllqazJjMFM0VjY1N1J6UzkwakorMWY3QTdBNHdwVUE3cWNaZXRxTlZMRUkweGw2QTdxS3g5S0VhRzI5Rmc9

Sim, é que na hora da raspagem ele obtem o primeiro link https://basseqwevewcewcewecwcw.xyz/video/450fc92852e1ca2963c0ee18e586c9c5

**Comment by icarok99** [comment]
Aqui um vídeo https://youtu.be/7-zqqc_2l-8?si=G94bjC1IhCVabxeK

**Comment by Huuuuuugo** [comment]
Ah sim, achei que ele chamava aqueles métodos resolvers na hora que escolhia uma opção. Se for só isso, basta chamar os resolvers no mesmo método do scraping. Vou arrumar rapidinho aqui.

**Comment by Huuuuuugo** [comment]
Mas quanto aos links de legendas? Tu sabe dizer como eles devem ser retornados? Eu retorno exatamente da mesma for que o resolver (com uma tupla com stream e legenda) ou ele entraria como terceiro elemento da tupla do link?
Exemplo:
(nome, (stream, legenda))
ou
(nome, stream, legenda)

**Comment by Huuuuuugo** [comment]
Vou fazer esse primeiro, que é mais fácil e tu testa aí.

**Comment by Huuuuuugo** [comment]
Acabei de mandar as alterações, essa forma de obter os links é bem mais lenta, mas parece que é assim que o kodi funciona. 
Testa aí.

**Comment by icarok99** [comment]
> Mas quanto aos links de legendas? Tu sabe dizer como eles devem ser retornados? Eu retorno exatamente da mesma for que o resolver (com uma tupla com stream e legenda) ou ele entraria como terceiro elemento da tupla do link? Exemplo: (nome, (stream, legenda)) ou (nome, stream, legenda)

stream e legenda

**Comment by icarok99** [comment]
Nome na reprodução fica responsável pelo banco de dados do tmdb

**Comment by icarok99** [comment]
CreateLoader - unsupported protocol([('https) in [('https://basseqwevewcewcewecwcw.xyz/video/7d73ce8d00ce8902a0c09d3d24d21194', 'https://subs.warezcdn.link/242264-PTB.srt')]

**Comment by icarok99** [comment]
> Acabei de mandar as alterações, essa forma de obter os links é bem mais lenta, mas parece que é assim que o kodi funciona. Testa aí.

Kodi é cheio de frescura

**Comment by Huuuuuugo** [comment]
> CreateLoader - unsupported protocol([('https) in [('https://basseqwevewcewcewecwcw.xyz/video/7d73ce8d00ce8902a0c09d3d24d21194', 'https://subs.warezcdn.link/242264-PTB.srt')]

Vou tentar fazer daquela outra forma.

**Comment by Huuuuuugo** [comment]
Acabei de mandar. Eu simplesmente modifiquei a estrutura dos dados retornados pelo scraper de `(nome, (stream, legenda))` pra `(nome, stream, legenda)`

**Comment by Huuuuuugo** [comment]
Ok, eu baixei o kodi pra testar aqui e descobri qual é o problema, a versão do `requests` que o thunder usa tem algum problema pra pegar o link da stream do vídeo. Eu testei com a versão mais recente e funcionou normalmente. Só não sei como que eu vou fazer pra atualizar essa versão usada no thunder.

**Comment by Huuuuuugo** [comment]
Acho que tem algo haver com o proxy que eles usam no `unblock`. Depois vejo se consigo arrumar isso.

**Comment by Huuuuuugo** [comment]
Acho que corrigi, daqui a pouco subo tudo lá pro repositório.

**Comment by icarok99** [comment]
> Acho que tem algo haver com o proxy que eles usam no `unblock`. Depois vejo se consigo arrumar isso.

Então foi por isso que o dev nunca mais atualizou o provedor warez.

**Comment by Huuuuuugo** [comment]
Tá lá, testei tudo no meu pc e funcionou direitinho. Quanto tu for instalar no teu, copia todos os arquivos, não só o `warez.py`. Por enquanto só o warezcdn tá funcionando.

**Comment by icarok99** [comment]
> Tá lá, testei tudo no meu pc e funcionou direitinho. Quanto tu for instalar no teu, copia todos os arquivos, não só o `warez.py`. Por enquanto só o warezcdn tá funcionando.

Tá de bom tamanho apenas warezcdn melhor que nada

**Comment by icarok99** [comment]
Muito obrigado por reviver o provedor warez

**Comment by Huuuuuugo** [comment]
De nada, foi legal trabalhar nisso. Acho que ainda vou tentar restaurar o mixdrop já que, aparentemente, as ferramentas pra isso já estão no addon.

**Comment by icarok99** [comment]
Codifica o unblock.

**Comment by icarok99** [comment]
> De nada, foi legal trabalhar nisso. Acho que ainda vou tentar restaurar o mixdrop já que, aparentemente, as ferramentas pra isso já estão no addon.

Caso não tenha como eu achei o github da versão antiga talvez com essa versão encontre o método para usar o addon resolverurl invés do arquivo resolver.py

https://github.com/zoreu/addon_thunder/blob/main/update_thunder_05_04_2022.zip

**Comment by Huuuuuugo** [comment]
> > De nada, foi legal trabalhar nisso. Acho que ainda vou tentar restaurar o mixdrop já que, aparentemente, as ferramentas pra isso já estão no addon.
> 
> Caso não tenha como eu achei o github da versão antiga talvez com essa versão encontre o método para usar o addon resolverurl invés do arquivo resolver.py
> 
> https://github.com/zoreu/addon_thunder/blob/main/update_thunder_05_04_2022.zip

Já achei uma função pra isso no arquivo `jsunpack.py` e já implementei a lógica pra pegar os links do mixdrop. O único problema é que esse link tem ser acessado pelo kodi com o mesmo cabeçalho que foi usado pra obter ele, e eu ainda não sei como fazer isso no kodi.
Resumindo, já tá tudo feito, só falta eu descobrir como especificar o cabeçalho que o kodi deve usar na requisição do vídeo. Quando eu descobrir como fazer isso, subo as mudanças pro repositório.

**Comment by icarok99** [comment]
> > De nada, foi legal trabalhar nisso. Acho que ainda vou tentar restaurar o mixdrop já que, aparentemente, as ferramentas pra isso já estão no addon.
> 
> Caso não tenha como eu achei o github da versão antiga talvez com essa versão encontre o método para usar o addon resolverurl invés do arquivo resolver.py
> 
> https://github.com/zoreu/addon_thunder/blob/main/update_thunder_05_04_2022.zip

Depois decodifique o provider.py dessa versão e coloque no branch test.

**Comment by Huuuuuugo** [comment]
Acabei de mandar lá pra branch `test` do repositório.
Também subi as alterações que tinha feito no `warez.py` pra extrair os links do mixdrop, só que ainda não tive tempo de corrigir aquilo de fazer o kodi usar os cabeçalhos certos na hora de pegar o vídeo, então o mixdrop ainda não funciona.

**Comment by icarok99** [comment]
Arrumei o mixdrop vou upar daqui a pouco no repositório, e pode deletar o repositório test.

**Comment by Huuuuuugo** [comment]
Boa. Eu acabei de terminar a primeira versão de um scraper pro redecanais, talvez no futuro dê pra adaptar ele pra funcionar no kodi.
